version: "3.12"
services:
  pytorch:
    build: .
    environment:
      - NVIDIA_VISIBLE_DEVICES=all  # or device number (e.g. 0) to allow a single gpu
    ports:
      - "60000:8888"  # port for JupyterLab (or JupyterNotebook)
      - "60001:22"  # port for ssh
    volumes:
      - /home/gabricp/tfg:/home/gabriel/tfg